In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# Get Dimension
a.ndim

1

In [5]:
b.ndim

2

In [6]:
# Get Shape
a.shape

(3,)

In [7]:
b.shape

(2, 3)

In [8]:
# Get Type
a.dtype

dtype('int32')

In [9]:
b.dtype

dtype('float64')

In [10]:
# Get Size
a.itemsize

4

In [11]:
b.itemsize

8

In [12]:
# Get Total Size
a.nbytes

12

In [13]:
b.nbytes

48

In [14]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [15]:
# Get a specific element [r, c]
a[1, 5]

13

In [16]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [17]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [18]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [19]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [20]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [21]:
# Get specific element (work outside in)
b[0,1,1]

4

In [22]:
# replace 
b[:,1,:] = [[9,9],[8,8]]

In [23]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [24]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [26]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [27]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [28]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.88715302, 0.03574087],
       [0.8518703 , 0.25522752],
       [0.32449819, 0.07112941],
       [0.14798707, 0.9209487 ]])

In [29]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 3,  3, -4],
       [ 5,  5,  6],
       [-4,  3,  7]])

In [30]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [32]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [33]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


In [34]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [35]:
a + 2

array([3, 4, 5, 6])

In [36]:
a - 2

array([-1,  0,  1,  2])

In [37]:
a * 2

array([2, 4, 6, 8])

In [38]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [39]:
a ** 2

array([ 1,  4,  9, 16])

In [40]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [41]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [43]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [44]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])